# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideauser',
            name='idea_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ideauser',
            name='idea_text',
            field=models.TextField(default=''),
        ),
    ]
