# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_auto_20170118_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideauser',
            name='idea_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ideauser',
            name='idea_text',
            field=models.TextField(),
        ),
    ]
