# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20170118_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideauser',
            name='idea_rank',
            field=models.CharField(max_length=200),
        ),
    ]
