# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20170118_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideauser',
            name='idea_rank',
            field=models.IntegerField(),
        ),
    ]
