# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_auto_20170118_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideauser',
            name='idea_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
